import 'package:flutter/material.dart';

import '../../../core/widgets/app_shell.dart';
import '../../../core/widgets/responsive_split_view.dart';
import '../../../core/widgets/section_card.dart';
import '../../../core/widgets/status_badge.dart';
import '../models/project_workflow_models.dart';

class ProjectDetailScreen extends StatelessWidget {
  const ProjectDetailScreen({
    super.key,
    this.project,
    required this.onOpenArtifact,
    required this.onDestinationSelected,
  });

  final ProjectWorkflowData? project;
  final ValueChanged<String> onOpenArtifact;
  final ValueChanged<int> onDestinationSelected;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final data = project;

    return AppShell(
      title: data?.name ?? 'Project Detail',
      selectedIndex: 1,
      onDestinationSelected: onDestinationSelected,
      child: data == null
          ? ListView(
              padding: const EdgeInsets.all(24),
              children: [
                SectionCard(
                  title: 'Workflow is loading',
                  subtitle: 'Project detail has not been resolved yet.',
                  child: Text(
                    'Refresh the page or return to the dashboard if this state persists.',
                    style: theme.textTheme.bodyLarge,
                  ),
                ),
              ],
            )
          : ListView(
              padding: const EdgeInsets.all(24),
              children: [
                SectionCard(
                  title: data.name,
                  subtitle: data.workspaceName,
                  trailing: StatusBadge(
                    label: data.status.label,
                    backgroundColor: statusColor(data.status, theme.colorScheme)
                        .withValues(alpha: 0.12),
                    foregroundColor:
                        statusColor(data.status, theme.colorScheme),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(data.goal, style: theme.textTheme.bodyLarge),
                      const SizedBox(height: 16),
                      LinearProgressIndicator(value: data.progress),
                      const SizedBox(height: 8),
                      Text('${(data.progress * 100).round()}% complete'),
                    ],
                  ),
                ),
                const SizedBox(height: 16),
                ResponsiveSplitView(
                  primary: SectionCard(
                    title: 'Execution plan',
                    subtitle: 'Ordered task pipeline',
                    child: Column(
                      children: data.executionPlan
                          .map(
                            (step) => _WorkflowStepTile(step: step),
                          )
                          .toList(),
                    ),
                  ),
                  secondary: Column(
                    children: [
                      SectionCard(
                        title: 'Agents',
                        subtitle: 'Role boundaries for the workflow',
                        child: Column(
                          children: data.agents
                              .map((agent) => _AgentTile(agent: agent))
                              .toList(),
                        ),
                      ),
                      const SizedBox(height: 16),
                      SectionCard(
                        title: 'Artifacts',
                        subtitle: 'Structured outputs generated by each step',
                        child: Column(
                          children: data.artifacts
                              .map(
                                (artifact) => _ArtifactTile(
                                  artifact: artifact,
                                  onOpen: () => onOpenArtifact(artifact.id),
                                ),
                              )
                              .toList(),
                        ),
                      ),
                      const SizedBox(height: 16),
                      SectionCard(
                        title: 'Execution logs',
                        subtitle: 'System trace and validation notes',
                        child: Column(
                          children: data.logs
                              .map((log) => _LogTile(entry: log))
                              .toList(),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
    );
  }
}

class _WorkflowStepTile extends StatelessWidget {
  const _WorkflowStepTile({required this.step});

  final WorkflowStepSummary step;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final color = stepColor(step.status, theme.colorScheme);

    return ListTile(
      contentPadding: EdgeInsets.zero,
      leading: CircleAvatar(
        backgroundColor: color.withValues(alpha: 0.12),
        foregroundColor: color,
        child: Text('${step.order}'),
      ),
      title: Text(step.title),
      subtitle: Text(step.description),
      trailing: StatusBadge(
        label: step.status.label,
        backgroundColor: color.withValues(alpha: 0.12),
        foregroundColor: color,
      ),
    );
  }
}

class _AgentTile extends StatelessWidget {
  const _AgentTile({required this.agent});

  final WorkflowAgentSummary agent;

  @override
  Widget build(BuildContext context) {
    return ListTile(
      contentPadding: EdgeInsets.zero,
      leading: CircleAvatar(child: Text(agent.role.label.substring(0, 1))),
      title: Text(agent.name),
      subtitle: Text(agent.capabilities.join(' - ')),
      trailing: Text(agent.status),
    );
  }
}

class _ArtifactTile extends StatelessWidget {
  const _ArtifactTile({
    required this.artifact,
    required this.onOpen,
  });

  final WorkflowArtifactSummary artifact;
  final VoidCallback onOpen;

  @override
  Widget build(BuildContext context) {
    return ListTile(
      contentPadding: EdgeInsets.zero,
      leading: const Icon(Icons.description_outlined),
      title: Text(artifact.title),
      subtitle: Text(artifact.description),
      trailing: TextButton(
        onPressed: onOpen,
        child: Text(artifact.type.label),
      ),
    );
  }
}

class _LogTile extends StatelessWidget {
  const _LogTile({required this.entry});

  final WorkflowLogEntry entry;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(
            entry.severity == LogSeverity.error
                ? Icons.error_outline
                : entry.severity == LogSeverity.warning
                    ? Icons.warning_amber_outlined
                    : Icons.info_outline,
            size: 18,
            color: entry.severity == LogSeverity.error
                ? theme.colorScheme.error
                : theme.colorScheme.secondary,
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(entry.message),
                const SizedBox(height: 4),
                Text(
                  '${entry.source} - ${entry.timestamp}',
                  style: theme.textTheme.bodySmall
                      ?.copyWith(color: theme.colorScheme.secondary),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
